### ISSUE TITLE
Basic login form

### ISSUE THREAD

**Issue by manyabansal406** [InnogeeksOrganization/recruitment#2]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basic login form</title>

</head>
<style>
    h1 {
        text-align: center;
        color: black;
        text-shadow: 5px;
        text-decoration: double;
    }
    
    body {
        margin: 100px;
        padding: 100px;
        background-color: white;
        border: 5px solid black;
    }
    
    * {
        box-sizing: 100px 150px;
        box-shadow: 50px;
        border-radius: 5px;
    }
    
    input[type="submit"] {
        width: 100%;
        text-align: center;
        border: 10px;
        border-radius: 5px;
        padding: 10px;
        background-color: blue;
    }
</style>

<body>
    <form>
        <h1>login form</h1>
        <h2>Information Required</h2>
        <p>First name:<input type="text" id="first_name"></p>
        <p>Last name:<input type="text" id="last_name"></p>
        <p>
            E-mail:<input type="email" id="email">
        </p>
        <p>Required fields are shown by*</p>
        <p>Phone number*: <input type="number" name="phone number"></p>
        <p>Alternate number*: <input type="number" name="alternate number"></p>
        <h2>Social media information</h2>
        <p> <input type="submit" value="submit"></p>

    </form>
</body>
</html>

**Comment by devAyushDubey** [comment]
Thank you for taking out your time Manya but this seems irrelevant here. This is just a repository containing Open Source Track information for Innogeeks Recruitment 2022.
